<?php

namespace Database\Seeders;

use App\Models\MasterUpt;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class MasterUptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'kode_satpel' => '0000',
                'kode_upt' => '00',
                'nama' => 'Kantor Pusat',
                'nama_en' => '',
                'wilayah_kerja' => 'Jakarta',
                'nama_satpel' => 'Kantor Pusat',
                'kota' => 'Jakarta',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 2,
                'kode_satpel' => '1100',
                'kode_upt' => '11',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Nangroe Aceh Darussalam',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Nanggroe Aceh Darussalam',
                'nama_satpel' => 'UPT Induk',
                'kota' => 'Banda Aceh',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 3,
                'kode_satpel' => '1101',
                'kode_upt' => '11',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Nangroe Aceh Darussalam',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Nanggroe Aceh Darussalam',
                'nama_satpel' => 'Bandara Iskandar Muda',
                'kota' => 'Banda Aceh',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 4,
                'kode_satpel' => '1102',
                'kode_upt' => '11',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Nangroe Aceh Darussalam',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Nanggroe Aceh Darussalam',
                'nama_satpel' => 'Pelabuhan Laut Sabang',
                'kota' => 'Banda Aceh',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 5,
                'kode_satpel' => '1103',
                'kode_upt' => '11',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Nangroe Aceh Darussalam',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Nanggroe Aceh Darussalam',
                'nama_satpel' => 'Pelabuhan Laut Lhokseumawe',
                'kota' => 'Banda Aceh',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 6,
                'kode_satpel' => '1104',
                'kode_upt' => '11',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Nangroe Aceh Darussalam',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Nanggroe Aceh Darussalam',
                'nama_satpel' => 'Pelabuhan Laut Meulaboh',
                'kota' => 'Banda Aceh',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 7,
                'kode_satpel' => '1105',
                'kode_upt' => '11',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Nangroe Aceh Darussalam',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Nanggroe Aceh Darussalam',
                'nama_satpel' => 'Pelabuhan Laut Sinabang',
                'kota' => 'Banda Aceh',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 8,
                'kode_satpel' => '1106',
                'kode_upt' => '11',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Nangroe Aceh Darussalam',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Nanggroe Aceh Darussalam',
                'nama_satpel' => 'Pelabuhan Laut Kuala Langsa',
                'kota' => 'Banda Aceh',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 9,
                'kode_satpel' => '1107',
                'kode_upt' => '11',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Nangroe Aceh Darussalam',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Nanggroe Aceh Darussalam',
                'nama_satpel' => 'Pelabuhan Laut Simeuleu',
                'kota' => 'Banda Aceh',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 10,
                'kode_satpel' => '1200',
                'kode_upt' => '12',
                'nama' => 'Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Sumatera Utara',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Utara',
                'nama_satpel' => 'UPT Induk',
                'kota' => 'Medan',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 11,
                'kode_satpel' => '1201',
                'kode_upt' => '12',
                'nama' => 'Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Sumatera Utara',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Utara',
                'nama_satpel' => 'Bandara Kualanamu',
                'kota' => 'Medan',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 12,
                'kode_satpel' => '1202',
                'kode_upt' => '12',
                'nama' => 'Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Sumatera Utara',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Utara',
                'nama_satpel' => 'Bandara Sisingamangaraja',
                'kota' => 'Medan',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 13,
                'kode_satpel' => '1203',
                'kode_upt' => '12',
                'nama' => 'Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Sumatera Utara',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Utara',
                'nama_satpel' => 'Pelabuhan Belawan',
                'kota' => 'Medan',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 14,
                'kode_satpel' => '1204',
                'kode_upt' => '12',
                'nama' => 'Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Sumatera Utara',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Utara',
                'nama_satpel' => 'Pelabuhan Tanjung Balai Asahan',
                'kota' => 'Medan',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 15,
                'kode_satpel' => '1205',
                'kode_upt' => '12',
                'nama' => 'Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Sumatera Utara',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Utara',
                'nama_satpel' => 'Pelabuhan Laut Sibolga',
                'kota' => 'Medan',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 16,
                'kode_satpel' => '1300',
                'kode_upt' => '13',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Sumatera Barat',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Barat',
                'nama_satpel' => 'UPT Induk',
                'kota' => 'Padang',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 17,
                'kode_satpel' => '1301',
                'kode_upt' => '13',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Sumatera Barat',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Barat',
                'nama_satpel' => 'Bandara Minangkabau',
                'kota' => 'Padang',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 18,
                'kode_satpel' => '1302',
                'kode_upt' => '13',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Sumatera Barat',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Sumatera Barat',
                'nama_satpel' => 'Pelabuhan Laut Mentawai',
                'kota' => 'Padang',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 19,
                'kode_satpel' => '1400',
                'kode_upt' => '14',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Riau',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Riau',
                'nama_satpel' => 'UPT Induk',
                'kota' => 'Pekanbaru',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            [
                'id' => 20,
                'kode_satpel' => '1401',
                'kode_upt' => '14',
                'nama' => 'Balai Karantina Hewan, Ikan, dan Tumbuhan Riau',
                'nama_en' => '',
                'wilayah_kerja' => 'Provinsi Riau',
                'nama_satpel' => 'Bandara Sultan Syarif Kasim II',
                'kota' => 'Pekanbaru',
                'kode_pelabuhan' => NULL,
                'tembusan' => NULL,
                'otoritas_pelabuhan' => NULL,
                'syah_bandar_pelabuhan' => NULL,
                'kepala_kantor_bea_cukai' => NULL,
                'nama_pengelola' => NULL,
                'stat_ppkol' => '',
                'stat_insw' => '',
                'created_at' => '2024-01-12 15:44:31',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],

        ];
        foreach ($data as $value) {
            unset($value['id'], $value['created_at'], $value['updated_at'], $value['deleted_at'], $value['stat_ppkol'], $value['stat_insw']);
            MasterUpt::create($value);
        }


    }
}
